// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using Microsoft.VisualBasic;

namespace Twinvision.Flow.Tests.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("Twinvision.Flow.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;div class=&quot;class1&quot; id=&quot;element1&quot;&gt;
        /// &lt;div class=&quot;class2&quot; id=&quot;element2&quot;&gt;
        /// &lt;div class=&quot;class3&quot; id=&quot;element3&quot;&gt;
        /// &lt;div class=&quot;class4&quot; id=&quot;element4&quot;&gt;
        /// &lt;div class=&quot;class5&quot; id=&quot;element5&quot;&gt;
        /// &lt;div class=&quot;class6&quot; id=&quot;element6&quot;&gt;
        /// &lt;div class=&quot;class7&quot; id=&quot;element7&quot;&gt;
        /// &lt;div class=&quot;class8&quot; id=&quot;element8&quot;&gt;
        /// &lt;div class=&quot;class9&quot; id=&quot;element9&quot;&gt;
        /// &lt;div cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssertEqualDeeplyNested
        {
            get
            {
                return ResourceManager.GetString("AssertEqualDeeplyNested", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;body&gt;Hello world!&lt;/body&gt;
        /// &lt;/html&gt;
        /// .
        /// </summary>
        internal static string AssertEqualHelloWorld
        {
            get
            {
                return ResourceManager.GetString("AssertEqualHelloWorld", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        /// &lt;html lang=&quot;en&quot;&gt;
        /// &lt;body&gt;
        /// &lt;!--
        /// A comment for
        /// a div element
        /// --&gt;
        /// &lt;div&gt;HTML comments test&lt;/div&gt;
        /// &lt;/body&gt;
        /// &lt;/html&gt;
        /// .
        /// </summary>
        internal static string AssertEqualMultiLineComment
        {
            get
            {
                return ResourceManager.GetString("AssertEqualMultiLineComment", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;DiV CLASS=&quot;Test&quot;&gt;Content&lt;/DiV&gt;
        /// .
        /// </summary>
        internal static string AssertEqualPreserveCase
        {
            get
            {
                return ResourceManager.GetString("AssertEqualPreserveCase", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        /// &lt;html lang=&quot;en&quot;&gt;
        /// &lt;body&gt;
        /// &lt;!-- A comment for a div element --&gt;
        /// &lt;div&gt;HTML comments test&lt;/div&gt;
        /// &lt;/body&gt;
        /// &lt;/html&gt;
        /// .
        /// </summary>
        internal static string AssertEqualSingleLineComment
        {
            get
            {
                return ResourceManager.GetString("AssertEqualSingleLineComment", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        /// &lt;html&gt;
        /// &lt;body&gt;Size 8&lt;/body&gt;
        /// &lt;/html&gt;
        /// .
        /// </summary>
        internal static string AssertEqualTabSize8
        {
            get
            {
                return ResourceManager.GetString("AssertEqualTabSize8", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;div class=&quot;component&quot;&gt;
        /// &lt;a href=&quot;http://www.google.com&quot; /&gt;
        /// &lt;/div&gt;
        /// .
        /// </summary>
        internal static string AssertSkipComments
        {
            get
            {
                return ResourceManager.GetString("AssertSkipComments", resourceCulture);
            }
        }
    }
}

