//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twinvision.Flow.Tests.My_Project.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;body&gt;
        ///        &lt;h1&gt;Component example&lt;/h1&gt;
        ///        &lt;!-- Begin My Component --&gt;
        ///        &lt;div class=&quot;Main component element&quot;&gt;
        ///            &lt;span&gt;Extra component content&lt;/span&gt;
        ///        &lt;/div&gt;
        ///        &lt;!-- End My Component --&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        public static string AssertCreateComponent {
            get {
                return ResourceManager.GetString("AssertCreateComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;Test&quot;&gt;Content&lt;/div&gt;
        ///.
        /// </summary>
        public static string AssertDoNotPreserveCase {
            get {
                return ResourceManager.GetString("AssertDoNotPreserveCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;class1&quot; id=&quot;element1&quot;&gt;
        ///    &lt;div class=&quot;class2&quot; id=&quot;element2&quot;&gt;
        ///        &lt;div class=&quot;class3&quot; id=&quot;element3&quot;&gt;
        ///            &lt;div class=&quot;class4&quot; id=&quot;element4&quot;&gt;
        ///                &lt;div class=&quot;class5&quot; id=&quot;element5&quot;&gt;
        ///                    &lt;div class=&quot;class6&quot; id=&quot;element6&quot;&gt;
        ///                        &lt;div class=&quot;class7&quot; id=&quot;element7&quot;&gt;
        ///                            &lt;div class=&quot;class8&quot; id=&quot;element8&quot;&gt;
        ///                                &lt;div class=&quot;class9&quot; id=&quot;element9&quot;&gt;
        ///                                    &lt;div cla [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AssertEqualDeeplyNested {
            get {
                return ResourceManager.GetString("AssertEqualDeeplyNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;body&gt;Hello world!&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        public static string AssertEqualHelloWorld {
            get {
                return ResourceManager.GetString("AssertEqualHelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;body&gt;
        ///        &lt;!--
        ///            A comment for
        ///            a div element
        ///        --&gt;
        ///        &lt;div&gt;HTML comments test&lt;/div&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        public static string AssertEqualMultiLineComment {
            get {
                return ResourceManager.GetString("AssertEqualMultiLineComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DiV CLASS=&quot;Test&quot;&gt;Content&lt;/DiV&gt;
        ///.
        /// </summary>
        public static string AssertEqualPreserveCase {
            get {
                return ResourceManager.GetString("AssertEqualPreserveCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;body&gt;
        ///        &lt;!-- A comment for a div element --&gt;
        ///        &lt;div&gt;HTML comments test&lt;/div&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        public static string AssertEqualSingleLineComment {
            get {
                return ResourceManager.GetString("AssertEqualSingleLineComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///        &lt;body&gt;Size 8&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        public static string AssertEqualTabSize8 {
            get {
                return ResourceManager.GetString("AssertEqualTabSize8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;test.js&quot;&gt;&lt;/script&gt;
        ///.
        /// </summary>
        public static string AssertNoSelfClosing {
            get {
                return ResourceManager.GetString("AssertNoSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;test.js&quot; /&gt;.
        /// </summary>
        public static string AssertSelfClosing {
            get {
                return ResourceManager.GetString("AssertSelfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;component&quot;&gt;
        ///    &lt;a href=&quot;http://www.google.com&quot;&gt;&lt;/a&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        public static string AssertSkipComments {
            get {
                return ResourceManager.GetString("AssertSkipComments", resourceCulture);
            }
        }
    }
}
