'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Twinvision.Flow.Tests.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&quot;class1&quot; id=&quot;element1&quot;&gt;
        '''    &lt;div class=&quot;class2&quot; id=&quot;element2&quot;&gt;
        '''        &lt;div class=&quot;class3&quot; id=&quot;element3&quot;&gt;
        '''            &lt;div class=&quot;class4&quot; id=&quot;element4&quot;&gt;
        '''                &lt;div class=&quot;class5&quot; id=&quot;element5&quot;&gt;
        '''                    &lt;div class=&quot;class6&quot; id=&quot;element6&quot;&gt;
        '''                        &lt;div class=&quot;class7&quot; id=&quot;element7&quot;&gt;
        '''                            &lt;div class=&quot;class8&quot; id=&quot;element8&quot;&gt;
        '''                                &lt;div class=&quot;class9&quot; id=&quot;element9&quot;&gt;
        '''                                    &lt;div cla [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AssertEqualDeeplyNested() As String
            Get
                Return ResourceManager.GetString("AssertEqualDeeplyNested", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''    &lt;body&gt;Hello world!&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property AssertEqualHelloWorld() As String
            Get
                Return ResourceManager.GetString("AssertEqualHelloWorld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''    &lt;body&gt;
        '''        &lt;!--
        '''            A comment for
        '''            a div element
        '''        --&gt;
        '''        &lt;div&gt;HTML comments test&lt;/div&gt;
        '''    &lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property AssertEqualMultiLineComment() As String
            Get
                Return ResourceManager.GetString("AssertEqualMultiLineComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;DiV CLASS=&quot;Test&quot;&gt;Content&lt;/DiV&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property AssertEqualPreserveCase() As String
            Get
                Return ResourceManager.GetString("AssertEqualPreserveCase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''    &lt;body&gt;
        '''        &lt;!-- A comment for a div element --&gt;
        '''        &lt;div&gt;HTML comments test&lt;/div&gt;
        '''    &lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property AssertEqualSingleLineComment() As String
            Get
                Return ResourceManager.GetString("AssertEqualSingleLineComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''        &lt;body&gt;Size 8&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property AssertEqualTabSize8() As String
            Get
                Return ResourceManager.GetString("AssertEqualTabSize8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div class=&quot;component&quot;&gt;
        '''    &lt;a href=&quot;http://www.google.com&quot; /&gt;
        '''&lt;/div&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property AssertSkipComments() As String
            Get
                Return ResourceManager.GetString("AssertSkipComments", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
