Friend Module HTMLTags

    Public Support As New SortedDictionary(Of String, Boolean()) From {
         {"a", New Boolean() {True, True, True, True, True}},
         {"abbr", New Boolean() {True, True, True, True, True}},
         {"acronym", New Boolean() {True, True, True, True, False}},
         {"address", New Boolean() {True, True, True, True, True}},
         {"applet", New Boolean() {False, True, False, True, False}},
         {"area", New Boolean() {False, True, True, True, True}},
         {"article", New Boolean() {False, False, False, False, True}},
         {"aside", New Boolean() {False, False, False, False, True}},
         {"audio", New Boolean() {False, False, False, False, True}},
         {"b", New Boolean() {True, True, True, True, True}},
         {"base", New Boolean() {True, True, True, True, True}},
         {"basefont", New Boolean() {False, True, False, True, False}},
         {"bdi", New Boolean() {False, False, False, False, True}},
         {"bdo", New Boolean() {False, True, True, True, True}},
         {"big", New Boolean() {True, True, True, True, False}},
         {"blockquote", New Boolean() {True, True, True, True, True}},
         {"body", New Boolean() {True, True, True, True, True}},
         {"br", New Boolean() {True, True, True, True, True}},
         {"button", New Boolean() {True, True, True, True, True}},
         {"canvas", New Boolean() {False, False, False, False, True}},
         {"caption", New Boolean() {True, True, True, True, True}},
         {"center", New Boolean() {False, True, False, True, False}},
         {"cite", New Boolean() {True, True, True, True, True}},
         {"code", New Boolean() {True, True, True, True, True}},
         {"col", New Boolean() {False, True, True, True, True}},
         {"colgroup", New Boolean() {False, True, True, True, True}},
         {"command", New Boolean() {False, False, False, False, True}},
         {"datalist", New Boolean() {False, False, False, False, True}},
         {"dd", New Boolean() {True, True, True, True, True}},
         {"del", New Boolean() {False, True, True, True, True}},
         {"details", New Boolean() {False, False, False, False, True}},
         {"dfn", New Boolean() {True, True, True, True, True}},
         {"dir", New Boolean() {False, True, False, True, False}},
         {"div", New Boolean() {True, True, True, True, True}},
         {"dl", New Boolean() {True, True, True, True, True}},
         {"dt", New Boolean() {True, True, True, True, True}},
         {"em", New Boolean() {True, True, True, True, True}},
         {"embed", New Boolean() {False, False, False, False, True}},
         {"fieldset", New Boolean() {True, True, True, True, True}},
         {"figcaption", New Boolean() {False, False, False, False, True}},
         {"figure", New Boolean() {False, False, False, False, True}},
         {"font", New Boolean() {False, True, False, True, False}},
         {"footer", New Boolean() {False, False, False, False, True}},
         {"form", New Boolean() {True, True, True, True, True}},
         {"frame", New Boolean() {False, True, False, False, False}},
         {"frameset", New Boolean() {False, True, False, False, False}},
         {"h1", New Boolean() {True, True, True, True, True}},
         {"h2", New Boolean() {True, True, True, True, True}},
         {"h3", New Boolean() {True, True, True, True, True}},
         {"h4", New Boolean() {True, True, True, True, True}},
         {"h5", New Boolean() {True, True, True, True, True}},
         {"h6", New Boolean() {True, True, True, True, True}},
         {"head", New Boolean() {True, True, True, True, True}},
         {"header", New Boolean() {False, False, False, False, True}},
         {"hgroup", New Boolean() {False, False, False, False, True}},
         {"hr", New Boolean() {True, True, True, True, True}},
         {"html", New Boolean() {True, True, True, True, True}},
         {"i", New Boolean() {True, True, True, True, True}},
         {"iframe", New Boolean() {False, True, False, True, True}},
         {"img", New Boolean() {True, True, True, True, True}},
         {"input", New Boolean() {True, True, True, True, True}},
         {"ins", New Boolean() {False, True, True, True, True}},
         {"kbd", New Boolean() {True, True, True, True, True}},
         {"keygen", New Boolean() {False, False, False, False, True}},
         {"label", New Boolean() {True, True, True, True, True}},
         {"legend", New Boolean() {True, True, True, True, True}},
         {"li", New Boolean() {True, True, True, True, True}},
         {"link", New Boolean() {True, True, True, True, True}},
         {"map", New Boolean() {False, True, True, True, True}},
         {"mark", New Boolean() {False, False, False, False, True}},
         {"menu", New Boolean() {False, True, False, True, True}},
         {"meta", New Boolean() {True, True, True, True, True}},
         {"meter", New Boolean() {False, False, False, False, True}},
         {"nav", New Boolean() {False, False, False, False, True}},
         {"noframes", New Boolean() {False, True, False, True, False}},
         {"noscript", New Boolean() {True, True, True, True, True}},
         {"object", New Boolean() {True, True, True, True, True}},
         {"ol", New Boolean() {True, True, True, True, True}},
         {"optgroup", New Boolean() {True, True, True, True, True}},
         {"option", New Boolean() {True, True, True, True, True}},
         {"output", New Boolean() {False, False, False, False, True}},
         {"p", New Boolean() {True, True, True, True, True}},
         {"param", New Boolean() {True, True, True, True, True}},
         {"pre", New Boolean() {True, True, True, True, True}},
         {"progress", New Boolean() {False, False, False, False, True}},
         {"q", New Boolean() {True, True, True, True, True}},
         {"rp", New Boolean() {False, False, False, False, True}},
         {"rt", New Boolean() {False, False, False, False, True}},
         {"ruby", New Boolean() {False, False, False, False, True}},
         {"s", New Boolean() {False, True, False, True, True}},
         {"samp", New Boolean() {True, True, True, True, True}},
         {"script", New Boolean() {True, True, True, True, True}},
         {"section", New Boolean() {False, False, False, False, True}},
         {"select", New Boolean() {True, True, True, True, True}},
         {"small", New Boolean() {True, True, True, True, True}},
         {"source", New Boolean() {False, False, False, False, True}},
         {"span", New Boolean() {True, True, True, True, True}},
         {"strike", New Boolean() {False, True, False, True, False}},
         {"strong", New Boolean() {True, True, True, True, True}},
         {"style", New Boolean() {True, True, True, True, True}},
         {"sub", New Boolean() {True, True, True, True, True}},
         {"summary", New Boolean() {False, False, False, False, True}},
         {"sup", New Boolean() {True, True, True, True, True}},
         {"table", New Boolean() {True, True, True, True, True}},
         {"tbody", New Boolean() {False, True, True, True, True}},
         {"td", New Boolean() {True, True, True, True, True}},
         {"textarea", New Boolean() {True, True, True, True, True}},
         {"tfoot", New Boolean() {False, True, True, True, True}},
         {"th", New Boolean() {True, True, True, True, True}},
         {"thead", New Boolean() {False, True, True, True, True}},
         {"time", New Boolean() {False, False, False, False, True}},
         {"title", New Boolean() {True, True, True, True, True}},
         {"tr", New Boolean() {True, True, True, True, True}},
         {"track", New Boolean() {False, False, False, False, True}},
         {"tt", New Boolean() {True, True, True, True, False}},
         {"u", New Boolean() {False, True, False, True, False}},
         {"ul", New Boolean() {True, True, True, True, True}},
         {"var", New Boolean() {True, True, True, True, True}},
         {"video", New Boolean() {False, False, False, False, True}},
         {"wbr", New Boolean() {False, False, False, False, True}}
     }

    ' Check for nesting. Also checks if an element is allowed just once or multiple times; tag:1 or tag:*
    Public Nesting As New SortedDictionary(Of String, String()) From {
        {"li", {"ul:*", "ol:*", "dir:*"}},
        {"body", {"html:1"}},
        {"head", {"html:1"}},
        {"title", {"head:1"}},
        {"link", {"head:*"}},
        {"meta", {"head:*"}},
        {"tr", {"table:*"}},
        {"td", {"tr:*"}},
        {"th", {"tr:*"}},
        {"caption", {"table:1"}},
        {"tfoot", {"table:1"}},
        {"tbody", {"table:1"}},
        {"thead", {"table:1"}},
        {"colgroup", {"table:*"}},
        {"col", {"colgroup:*"}},
        {"dt", {"dl:*"}},
        {"dd", {"dt:*"}},
        {"source", {"audio:*", "video:*"}},
        {"track", {"audio:*", "video:*"}},
        {"frame", {"frameset:*"}},
        {"noframes", {"frameset:1"}},
        {"option", {"select:*", "datalist:*", "optgroup:*"}},
        {"optgroup", {"select:*"}},
        {"summary", {"details:1"}},
        {"legend", {"fieldset:1"}},
        {"figcaption", {"figure:1"}},
        {"area", {"map:*"}}
    }

    Public SelfClosing As New List(Of String) From {
        "area", "base", "br", "col", "command", "embed", "hr", "img", "input", "keygen", "link", "meta", "param", "source", "track", "wbr"
    }

End Module
